### ISSUE TITLE
Regarding Omero RDF turtle file. missing linkage of Annotaion. 

### ISSUE THREAD

**Issue by ArghaSarker** [German-BioImaging/omero-rdf#16]
issue 1: 

i have noticed that, inside Omero-RDF file, not all the nodes are connected. 
for example, project, dataset, image, pixels. all those nodes are connected. and If I have a annotation for this nodes, the connection triples in "haspart" and "isPartof" missing.  while creating a graph visualization out of it, i can see that, it sees it as a separate graph, not connected. 

in this graph, the annotations are represented as a different map. 

![original](https://github.com/German-BioImaging/omero-rdf/assets/64970159/82029ee2-6e09-476e-b273-75ca752fbcf6)

this is the same graph, after connecting the map annotation and declaring the relationship with haspart . 

![after_adding_linkage](https://github.com/German-BioImaging/omero-rdf/assets/64970159/e7b5f03f-7afa-498d-9b02-7b5722865b64)

**Comment by joshmoore** [comment]
Hi @ArghaSarker. Thanks for opening the issue! It looks like each of the calls to `handler(annotation)` like at https://github.com/German-BioImaging/omero-rdf/blob/main/src/omero_rdf/__init__.py#L439C17-L439C36 are going to need `emit()` calls **OR** we refactor the emitting of `hasPart` etc. within the handler `__call__` itself.

**Comment by andrawaag** [comment]
I stumbled on the same issue. I was able to extract the link with the following sparql query. 
```PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ome-xml: <http://www.openmicroscopy.org/Schemas/OME/2016-06#>
PREFIX ome: <http://www.openmicroscopy.org/rdf/2016-06/ome_core/>

SELECT ?annotation ?user ?datasetLabel ?datasetLabelAnnotation WHERE {
    VALUES ?user {"kapongo.lumamba"}
    ?annotation rdf:type ome-xml:MapAnnotation ;
              ome:Map [ome:Key "User" ; ome:Value ?user] .
   ?annotation ome:Map [ome:Key "Dataset" ; ome:Value ?datasetLabelAnnotation] .
   ?dataset ome:Name ?datasetLabel .
    FILTER (?datasetLabelAnnotation = ?datasetLabel)
        

} LIMIT 10```

I was thinking of fixing this with a CONSTRUCT query, but I am not sure how many `ome:Key` I need to consider to get all links to an Annotation
